package ZoneSeek.common;

import net.minecraftforge.common.Configuration;

public class IDsHelper {
	
	//Configuration categories
	public static String blockids = "Block IDs";
	public static String itemids = "Item IDs";
	public static String biomeids = "Biome IDs";
	
	//Biome IDs
	public static int LagoonID;
	public static int SludgeID;

	//Block IDs
	public static int ApophylliteID;
	public static int AxiniteID;
	public static int BetafiteID;
	public static int BrochantiteID;
	public static int CarpetRedID;
	public static int CoconutBlockID;
	public static int CounterID;
	public static int DolomiteID;
	public static int FotiteID;
	public static int GraniteID;
	public static int HardWoodID;
	public static int HeterogeniteID;
	public static int InfectedBlockID;
	public static int InfectedBrickID;
	public static int InfectedLampID;
	public static int InfectedOreID;
	public static int KasoliteID;
	public static int LagoonDirtID;
	public static int LagoonGrassID;
	public static int LagoonLadderID;
	public static int LagoonLeafID;
    public static int LagoonLogID;
    public static int LagoonPlanksID;
    public static int LagoonSaplingID;
    public static int LagoonTallGrassID;
    public static int LagoonVinesID;
    public static int LazuriteID;
    public static int PalmLeafID;
    public static int PalmWoodPlanksID;
    public static int PalmLogID;
    public static int SidingID;
    public static int SludgeBrickID;
    public static int SludgeDirtID;
    public static int SludgeGrassID;
    public static int SludgeLampID;
    public static int SludgeLeafID;
    public static int SludgeLogID;
    public static int SludgeOreID;
    public static int SludgePlanksID;
    public static int SludgeRockID;
    public static int SludgeStoneGroundID;
    public static int SludgeTallGrassID;
    public static int TileID;
    public static int TropicalDirtID;
    public static int TropicalGrassID;
    public static int TropicalTallGrassID;
    public static int WallPaperBlueID;
    public static int WallPaperBlueBottomID;
    public static int WallPaperGreenID;
    public static int WallPaperGreenBottomID;
    public static int WallPaperRedID;
    public static int WallPaperRedBottomID;
    public static int WallPaperWhiteID;
    public static int WallPaperYellowID;
    public static int WallPaperYellowBottomID;
    public static int LagoonStairsID;
    public static int SludgeStairsID;
    public static int GraniteStairsID;
    public static int BloodFlowerID;
    public static int BlossomsID;
    public static int DaisyID;
    public static int DeadFlowerID;
    public static int IrisID;
    public static int SpringFlowersID;
    public static int TulipID;
    
    
    

	//Item IDs
	public static int ApophylliteCrystalID;
	public static int AxiniteCrystalID;
	public static int BananaID;
	public static int BetafiteCrystalID;
	public static int BookOfInfectionID;
	public static int BrochantiteCrystalID;
	public static int CoconutChunkID;
	public static int CompactedScaleFragmentID;
	public static int CompactedScalePlateID;
	public static int DolomiteCrystalID;
	public static int DragonFruitID;
	public static int FotiteCrystalID;
	public static int FuzzleChopID;
	public static int HeterogeniteCrystalID;
	public static int InfectedArrowID;
	public static int InfectedAxeID;
	public static int InfectedBattleAxeID;
	public static int InfectedBootsID;
	public static int InfectedBowID;
	public static int InfectedChestplateID;
	public static int InfectedGemID;
	public static int InfectedHelmetID;
	public static int InfectedHoeID;
	public static int InfectedLeggingsID;
	public static int InfectedPaxcelID;
	public static int InfectedPickaxeID;
	public static int InfectedPlateID;
	public static int InfectedProdID;
	public static int InfectedShardID;
	public static int InfectedSpadeID;
	public static int InfectedStickID;
	public static int InfectedStoneID;
	public static int InfectedSwordID;
	public static int KasoliteCrystalID;
	public static int LagoonScaleID;
	public static int LagoonStickID;
	public static int LazuriteCrystalID;
	public static int ObsidianStickID;
	public static int PearID;
	public static int PincerScaleID;
	public static int PineappleID;
	public static int PlumID;
	public static int SludgeGemID;
	public static int SludgeKatanaID;
	public static int SludgeShardID;
	public static int SludgeStoneID;
	public static int SlugSlimeID;
	public static int TaintedInkDropID;
	public static int TaintedInkSackID;
	public static int TaintedLeatherID;
	public static int TaintedPageID;
	
	public static int ApophylliBladeID;
	public static int ApophylliteAxeID;
	public static int ApophyllitePickaxeID;
	public static int ApophylliteShardID;
	public static int ApophylliteSpadeID;
	public static int AxiBladeID;
	public static int AxiniteAxeID;
	public static int AxinitePickaxeID;
	public static int AxiniteShardID;
	
	public static int AxiniteSpadeID;
	public static int BetaBladeID;
	public static int BetafiteAxeID;
	public static int BetafitePickaxeID;
	public static int BetafiteShardID;
	public static int BetafiteSpadeID;
	public static int BlueDyeID;
	public static int BroBladeID;
	public static int BrochantiteAxeID;
	public static int BrochantitePickaxeID;
	
	public static int BrochantiteShardID;
	public static int BrochantiteSpadeID;
	public static int CrimsonDyeID;
	public static int DoloBladeID;
	public static int DolomiteAxeID;
	public static int DolomitePickaxeID;
	public static int DolomiteShardID;
	public static int DolomiteSpadeID;
	public static int FoeBladeID;
	public static int FotiteAxeID;
	
	public static int FotitePickaxeID;
	public static int FotiteShardID;
	public static int FotiteSpadeID;
	public static int GeniteBladeID;
	public static int GrayDyeID;
	public static int GreenDyeID;
	public static int HeterogeniteAxeID;
	public static int HeterogenitePickaxeID;
	public static int HeterogeniteShardID;
	public static int HeterogeniteSpadeID;
	
	public static int KasoBladeID;
	public static int KasoliteAxeID;
	public static int KasolitePickaxeID;
	public static int KasoliteShardID;
	public static int KasoliteSpadeID;
	public static int LazarusBladeID;
	public static int LazuriteAxeID;
	public static int LazuritePickaxeID;
	public static int LazuriteShardID;
	public static int LazuriteSpadeID;
	
	public static int MasterCrystalID;
	public static int PinkDyeID;
	public static int RedDyeID;
	public static int ScaleBootsID;
	public static int ScaleChestplateID;
	public static int ScaleHelmetID;
	public static int ScaleLeggingsID;
	public static int SlimeCannonID;
	public static int SlimeClubID;
	public static int SlimeStabberID;
	
	public static int SludgeAxeID;
	public static int SludgeHammerID;
	public static int SludgeHoeID;
	public static int SludgePickaxeID;
	public static int SludgeSickleID;
	public static int SludgeSpadeID;
	public static int YellowDyeID;
	
	public static void runConfiguration(Configuration config){
		//Biome IDs
		LagoonID = config.get(biomeids, "Lagoon ID", 23).getInt();
		SludgeID = config.get(biomeids, "Sludge ID", 22).getInt();
		
		//Block IDs
		ApophylliteID = config.get(blockids, "Apophyllite ID", 700).getInt();
		AxiniteID = config.get(blockids, "Axinite ID", 701).getInt();
		BetafiteID = config.get(blockids, "Betafite ID", 702).getInt();
		BrochantiteID = config.get(blockids, "Brochantite ID", 703).getInt();
		CarpetRedID = config.get(blockids, "Carpet Red ID", 704).getInt();
		CoconutBlockID = config.get(blockids, "Coconut Block ID", 705).getInt();
		CounterID = config.get(blockids, "Counter ID", 706).getInt();
		DolomiteID = config.get(blockids, "Dolomite ID", 707).getInt();
		FotiteID = config.get(blockids, "Fotite ID", 708).getInt();
		GraniteID = config.get(blockids, "Granite ID", 709).getInt();
		HardWoodID = config.get(blockids, "Hard Wood ID", 710).getInt();
		HeterogeniteID = config.get(blockids, "Heterogenite ID", 711).getInt();
		InfectedBlockID = config.get(blockids, "Infected Block ID", 712).getInt();
		InfectedBrickID = config.get(blockids, "Infected Brick ID", 713).getInt();
		InfectedLampID = config.get(blockids, "Infected Lamp ID", 714).getInt();
		InfectedOreID = config.get(blockids, "Infected Ore ID", 715).getInt();
		KasoliteID = config.get(blockids, "Kasolite ID", 716).getInt();
		LagoonDirtID = config.get(blockids, "Lagoon Dirt ID", 250).getInt();
		LagoonGrassID = config.get(blockids, "Lagoon Grass ID", 251).getInt();
		LagoonLadderID = config.get(blockids, "LagoonLadder ID", 803).getInt();
		LagoonLeafID = config.get(blockids, "Lagoon Leaf ID", 804).getInt();
        LagoonLogID = config.get(blockids, "Lagoon Log ID", 806).getInt();
		LagoonPlanksID = config.get(blockids, "Lagoon Planks ID", 807).getInt();
		LagoonSaplingID = config.get(blockids, "Lagoon Sappling ID", 808).getInt();
		LagoonTallGrassID = config.get(blockids, "Lagoon Tall Grass ID", 170).getInt();
		LagoonVinesID = config.get(blockids, "Lagoon Vines ID", 247).getInt();
		LazuriteID = config.get(blockids, "Lazurite ID", 811).getInt();
		PalmLeafID = config.get(blockids, "Palm Leaf ID", 812).getInt();
		PalmWoodPlanksID = config.get(blockids, "Palm Wood Planks ID", 813).getInt();
		PalmLogID = config.get(blockids, "Palm Log ID", 814).getInt();
		SidingID = config.get(blockids, "Siding ID", 815).getInt();
		SludgeBrickID = config.get(blockids, "Sludge Brick ID", 816).getInt();
		SludgeDirtID = config.get(blockids, "Sludge Dirt ID", 254).getInt();
		SludgeGrassID = config.get(blockids, "Sludge Grass ID", 178).getInt();
		SludgeLampID = config.get(blockids, "Sludge Lamp ID", 819).getInt();
		SludgeLeafID = config.get(blockids, "Sludge Leaf ID", 820).getInt();
		SludgeLogID = config.get(blockids, "Sludge Log ID", 821).getInt();
		SludgeOreID = config.get(blockids, "Sludge Ore ID", 822).getInt();
		SludgePlanksID = config.get(blockids, "Sludge Planks ID", 823).getInt();
		SludgeRockID = config.get(blockids, "Sludge Rock ID", 824).getInt();
		SludgeStoneGroundID = config.get(blockids, "Sludge Stone Ground ID", 171).getInt();
		SludgeTallGrassID = config.get(blockids, "Sludge Tall Grass ID", 253).getInt();
		TileID = config.get(blockids, "Tile ID", 827).getInt();
		TropicalDirtID = config.get(blockids, "Tropical Dirt ID", 828).getInt();
		TropicalGrassID = config.get(blockids, "Tropical Grass ID", 829).getInt();
		WallPaperBlueID = config.get(blockids, "WallPaper Blue ID", 830).getInt();
		WallPaperBlueBottomID = config.get(blockids, "WallPaper Blue Bottom ID", 831).getInt();
		WallPaperGreenID = config.get(blockids, "WallPaper Green ID", 832).getInt();
		WallPaperGreenBottomID = config.get(blockids, "WallPaper Green Bottom ID", 833).getInt();
		WallPaperRedID = config.get(blockids, "WallPaper Red ID", 834).getInt();
		WallPaperRedBottomID = config.get(blockids, "WallPaper Red Bottom ID", 835).getInt();
		WallPaperWhiteID = config.get(blockids, "WallPaper WhiteID", 836).getInt();
		WallPaperYellowID = config.get(blockids, "WallPaper Yellow ID", 837).getInt();
		WallPaperYellowBottomID = config.get(blockids, "WallPaper Yellow Bottom ID", 838).getInt();
		TropicalTallGrassID = config.get(blockids, "Tropical Tall Grass ID", 839).getInt();
		LagoonStairsID = config.get(blockids, "Lagoon Stairs ID", 840).getInt();
		SludgeStairsID = config.get(blockids, "Sludge Stairs ID", 841).getInt();
		GraniteStairsID = config.get(blockids, "Granite Stairs ID", 842).getInt();		
		BloodFlowerID = config.get(blockids, "Blood Flower ID", 172).getInt();
		BlossomsID = config.get(blockids, "Blossoms ID", 173).getInt();
		DaisyID = config.get(blockids, "Daisy ID", 174).getInt();
		DeadFlowerID = config.get(blockids, "Dead Flower ID", 175).getInt();
		IrisID = config.get(blockids, "Iris ID", 176).getInt();
		SpringFlowersID = config.get(blockids, "Spring Flowers ID", 177).getInt();
		TulipID = config.get(blockids, "TulipID", 179).getInt();
		
		//Item IDs
		ApophylliteCrystalID = config.get(itemids, "Apophyllite Crystal ID", 1000).getInt();
		AxiniteCrystalID = config.get(itemids, "Axinite Crystal ID", 1001).getInt();
		BananaID = config.get(itemids, "Banana ID", 1002).getInt();
		BetafiteCrystalID = config.get(itemids, "Betafite Crystal ID", 1003).getInt();
		BookOfInfectionID = config.get(itemids, "Book Of Infection", 1004).getInt();
		BrochantiteCrystalID = config.get(itemids, "Brochantite Crystal ID", 1005).getInt();
		CoconutChunkID = config.get(itemids, "Coconut Chunk ID", 1006).getInt();
		CompactedScaleFragmentID = config.get(itemids, "Compacted Scale Fragment ID", 1007).getInt();
		CompactedScalePlateID = config.get(itemids, "Compacted Scale Plate ID", 1008).getInt();
		DolomiteCrystalID = config.get(itemids, "Dolomite Crystal ID", 1009).getInt();
		DragonFruitID = config.get(itemids, "Dragon Fruit ID", 1010).getInt();
		FotiteCrystalID = config.get(itemids, "Fotite Crystal ID", 1011).getInt();
		FuzzleChopID = config.get(itemids, "Fuzzle Chop ID", 1012).getInt();
		HeterogeniteCrystalID = config.get(itemids, "Heterogenite Crystal ID", 1013).getInt();
		InfectedArrowID = config.get(itemids, "Infected Arrow ID", 1014).getInt();
		InfectedAxeID = config.get(itemids, "Infected Axe ID", 1015).getInt();
		InfectedBattleAxeID = config.get(itemids, "Infected Battle Axe ID", 1016).getInt();
		InfectedBootsID = config.get(itemids, "Infected Boots ID", 1017).getInt();
		InfectedBowID = config.get(itemids, "Infected Bow ID", 1018).getInt();
		InfectedChestplateID = config.get(itemids, "Infected Chestplate ID", 1019).getInt();
		InfectedGemID = config.get(itemids, "Infected Gem ID", 1020).getInt();
		InfectedHelmetID = config.get(itemids, "Infected Helmet ID", 1021).getInt();
		InfectedHoeID = config.get(itemids, "Infected Hoe ID", 1022).getInt();
		InfectedPaxcelID = config.get(itemids, "Infected Paxcel ID", 1023).getInt();
		InfectedPickaxeID = config.get(itemids, "Infected Pickaxe ID", 1024).getInt();
		InfectedPlateID = config.get(itemids, "Infected Plate ID", 1025).getInt();
		InfectedProdID = config.get(itemids, "Infected Prod ID", 1026).getInt();
		InfectedShardID = config.get(itemids, "Infected Shard ID", 1027).getInt();
		InfectedSpadeID = config.get(itemids, "Infected Spade ID", 1028).getInt();
		InfectedStickID = config.get(itemids, "Infected Stick ID", 1029).getInt();
		InfectedStoneID = config.get(itemids, "Infected Stone ID", 1030).getInt();
		InfectedSwordID = config.get(itemids, "Infected Sword ID", 1031).getInt();
		KasoliteCrystalID = config.get(itemids, "Kasolite Crystal ID", 1032).getInt();
		LagoonScaleID = config.get(itemids, "Lagoon Scale ID", 1033).getInt();
		LazuriteCrystalID = config.get(itemids, "LazuriteCrystalID", 1034).getInt();
		ObsidianStickID = config.get(itemids, "Obsidian Stick ID", 1035).getInt();
		PearID = config.get(itemids, "Pear ID", 1036).getInt();
		PincerScaleID = config.get(itemids, "Pincer Scale ID", 1037).getInt();
		PineappleID = config.get(itemids, "Pineapple ID", 1038).getInt();
		PlumID = config.get(itemids, "Plum ID", 1039).getInt();
		SludgeKatanaID = config.get(itemids, "Sludge Katana ID", 1040).getInt();
		SludgeShardID = config.get(itemids, "Sludge Shard ID", 1041).getInt();
		SludgeStoneID = config.get(itemids, "Sludge Stone ID", 1042).getInt();
		SlugSlimeID = config.get(itemids, "Slug Slime ID", 1043).getInt();
		TaintedInkDropID = config.get(itemids, "Tainted Ink Drop ID", 1044).getInt();
		TaintedInkSackID = config.get(itemids, "Tainted Ink Sack ID", 1045).getInt();
		TaintedLeatherID = config.get(itemids, "Tainted Leather ID", 1046).getInt();
		TaintedPageID = config.get(itemids, "Tainted Page ID", 1047).getInt();
		SludgeGemID = config.get(itemids, "Sludge Gem ID", 1048).getInt();
		InfectedLeggingsID = config.get(itemids, "Infected Leggings ID", 1049).getInt();
		LagoonStickID = config.get(itemids, "Lagoon Stick ID", 1050).getInt();
		ApophylliBladeID = config.get(itemids, "Apophylli Blade ID", 1051).getInt();
		ApophylliteAxeID = config.get(itemids, "Apophyllite Axe ID", 1052).getInt();
		ApophyllitePickaxeID = config.get(itemids, "Apophyllite Pickaxe ID", 1053).getInt();
		ApophylliteSpadeID = config.get(itemids, "Apophyllite Spade ID", 1054).getInt();
		AxiBladeID = config.get(itemids, "Axi Blade ID", 1055).getInt();
		AxiniteAxeID = config.get(itemids, "Axinite Axe ID", 1056).getInt();
		AxinitePickaxeID = config.get(itemids, "Axinite Pickaxe ID", 1057).getInt();
		AxiniteSpadeID = config.get(itemids, "Axinite Spade ID;", 1058).getInt();
		BetaBladeID = config.get(itemids, "Beta Blade ID", 1059).getInt();
		BetafiteAxeID = config.get(itemids, "Betafite Axe ID", 1060).getInt();
		BetafitePickaxeID = config.get(itemids, "Betafite Pickaxe ID", 1061).getInt();
		BetafiteSpadeID = config.get(itemids, "Betafite Spade ID", 1062).getInt();
		BroBladeID = config.get(itemids, "Bro Blade ID", 1063).getInt();
		BrochantiteAxeID = config.get(itemids, "Brochantite Axe ID", 1064).getInt();
		BrochantitePickaxeID = config.get(itemids, "Brochantite Pickaxe ID", 1065).getInt();
		BrochantiteSpadeID = config.get(itemids, "Brochantite Spade ID", 1066).getInt();
		DoloBladeID = config.get(itemids, "Dolo Blade ID", 1067).getInt();
		DolomiteAxeID = config.get(itemids, "Dolomite Axe ID", 1068).getInt();
		DolomitePickaxeID = config.get(itemids, "Dolomite Pickaxe ID;", 1069).getInt();
		DolomiteSpadeID = config.get(itemids, "Dolomite Spade ID", 1070).getInt();
		FoeBladeID = config.get(itemids, "Foe Blade ID", 1071).getInt();
		FotiteAxeID = config.get(itemids, "Fotite Axe ID", 1072).getInt();
		FotitePickaxeID = config.get(itemids, "Fotite Pickaxe ID", 1073).getInt();
		FotiteSpadeID = config.get(itemids, "Fotite Spade ID", 1074).getInt();
		GeniteBladeID = config.get(itemids, "Genite Blade ID", 1075).getInt();
		HeterogeniteAxeID = config.get(itemids, "Heterogenite Axe ID", 1076).getInt();
		HeterogenitePickaxeID = config.get(itemids, "Heterogenite Pickaxe ID", 1077).getInt();
		HeterogeniteSpadeID = config.get(itemids, "Heterogenite Spade ID", 1078).getInt();
		KasoBladeID = config.get(itemids, "Kaso Blade ID", 1079).getInt();
		KasoliteAxeID = config.get(itemids, "Kasolite Axe ID", 1080).getInt();
		KasolitePickaxeID = config.get(itemids, "Kasolite Pickaxe ID", 1081).getInt();
		KasoliteSpadeID = config.get(itemids, "Kasolite Spade ID", 1082).getInt();
		LazarusBladeID = config.get(itemids, "Lazarus Blade ID", 1083).getInt();
		LazuriteAxeID = config.get(itemids, "Lazurite Axe ID", 1084).getInt();
		LazuritePickaxeID = config.get(itemids, "Lazurite Pickaxe ID", 1085).getInt();
		LazuriteSpadeID = config.get(itemids, "Lazurite Spade ID", 1086).getInt();
		ApophylliteShardID = config.get(itemids, "Apophyllite Shard ID", 1087).getInt();
		AxiniteShardID = config.get(itemids, "Axinite Shard ID", 1088).getInt();
		BetafiteShardID = config.get(itemids, "Betafite Shard ID", 1089).getInt();
		BlueDyeID = config.get(itemids, "Blue Dye ID", 1090).getInt();
		BrochantiteShardID = config.get(itemids, "Brochantite Shard ID", 1091).getInt();
		CrimsonDyeID = config.get(itemids, "Crimson Dye ID", 1092).getInt();
		DolomiteShardID = config.get(itemids, "Dolomite Shard ID", 1093).getInt();
		FotiteShardID = config.get(itemids, "Fotite Shard ID", 1094).getInt();
		GrayDyeID = config.get(itemids, "Gray Dye ID", 1095).getInt();
		GreenDyeID = config.get(itemids, "Green Dye ID", 1096).getInt();
		HeterogeniteShardID = config.get(itemids, "Heterogenite Shard ID", 1097).getInt();
		KasoliteShardID = config.get(itemids, "Kasolite Shard ID", 1098).getInt();
		LazuriteShardID = config.get(itemids, "Lazurite Shard ID", 1099).getInt();
		MasterCrystalID = config.get(itemids, "Master Crystal ID", 1100).getInt();
		PinkDyeID = config.get(itemids, "Pink Dye ID", 1101).getInt();
		RedDyeID = config.get(itemids, "Red Dye ID", 1102).getInt();
		ScaleBootsID = config.get(itemids, "Scale Boots ID", 1103).getInt();
		ScaleChestplateID = config.get(itemids, "Scale Chestplate ID", 1104).getInt();
		ScaleHelmetID = config.get(itemids, "Scale Helmet ID", 1105).getInt();
		ScaleLeggingsID = config.get(itemids, "Scale Leggings ID", 1106).getInt();
		SlimeCannonID = config.get(itemids, "Slime Cannon ID", 1107).getInt();
		SlimeClubID = config.get(itemids, "Slime Club ID", 1108).getInt();
		SlimeStabberID = config.get(itemids, "Slime Stabber ID", 1109).getInt();
		SludgeAxeID = config.get(itemids, "Sludge Axe ID", 1110).getInt();
		SludgeHammerID = config.get(itemids, "Sludge Hammer ID", 1111).getInt();
		SludgeHoeID = config.get(itemids, "Sludge Hoe ID", 1112).getInt();
		SludgePickaxeID = config.get(itemids, "Sludge Pickaxe ID", 1113).getInt();
		SludgeSickleID = config.get(itemids, "Sludge Sickle ID", 1114).getInt();
		SludgeSpadeID = config.get(itemids, "Sludge Spade ID", 1115).getInt();
		YellowDyeID = config.get(itemids, "Yellow Dye ID", 1115).getInt();
		
		
	}
	
}