package ZoneSeek.common.items;

import net.minecraft.item.EnumArmorMaterial;
import net.minecraft.item.EnumToolMaterial;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraftforge.common.EnumHelper;
import ZoneSeek.client.ClientProxyZoneSeek;
import ZoneSeek.common.CommonProxyZoneSeek;
import ZoneSeek.common.IDsHelper;
import ZoneSeek.common.ZoneSeek;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

public class ItemsHelper{
	
	@SidedProxy(clientSide = "ZoneSeek.client.ClientProxyZoneSeek", serverSide = "ZoneSeek.common.CommonProxyZoneSeek")
	public static CommonProxyZoneSeek proxy;

	//Items
	public static Item ApophylliteCrystal;
	public static Item AxiniteCrystal;
	public static Item Banana;
	public static Item BetafiteCrystal;
	public static Item BookOfInfection;
	public static Item BrochantiteCrystal;
	public static Item CoconutChunk;
	public static Item CompactedScaleFragment;
	public static Item CompactedScalePlate;
	public static Item DolomiteCrystal;
	public static Item DragonFruit;
	public static Item FotiteCrystal;
	public static Item FuzzleChop;
	public static Item HeterogeniteCrystal;
	public static Item InfectedArrow;
	public static Item InfectedAxe;
	public static Item InfectedBattleAxe;
	public static Item InfectedBoots;
	public static Item InfectedBow;
	public static Item InfectedChestplate;
	public static Item InfectedGem;
	public static Item InfectedHelmet;
	public static Item InfectedHoe;
	public static Item InfectedLeggings;
	public static Item InfectedPaxcel;
	public static Item InfectedPickaxe;
	public static Item InfectedPlate;
	public static Item InfectedProd;
	public static Item InfectedShard;
	public static Item InfectedSpade;
	public static Item InfectedStick;
	public static Item InfectedStone;
	public static Item InfectedSword;
	public static Item KasoliteCrystal;
	public static Item LagoonScale;
	public static Item LagoonStick;
	public static Item LazuriteCrystal;
	public static Item ObsidianStick;
	public static Item Pear;
	public static Item PincerScale;
	public static Item Pineapple;
	public static Item Plum;
	public static Item SludgeGem;
	public static Item SludgeKatana;
	public static Item SludgeShard;
	public static Item SludgeStone;
	public static Item SlugSlime;
	public static Item TaintedInkDrop;
	public static Item TaintedInkSack;
	public static Item TaintedLeather;
	public static Item TaintedPage;
	public static Item ApophylliBlade;
	public static Item ApophylliteAxe;
	public static Item ApophyllitePickaxe;
	public static Item ApophylliteShard;
	public static Item ApophylliteSpade;
	public static Item AxiBlade;
	public static Item AxiniteAxe;
	public static Item AxinitePickaxe;
	public static Item AxiniteShard;
	public static Item AxiniteSpade;
	public static Item BetaBlade;
	public static Item BetafiteAxe;
	public static Item BetafitePickaxe;
	public static Item BetafiteShard;
	public static Item BetafiteSpade;
	public static Item BlueDye;
	public static Item BroBlade;
	public static Item BrochantiteAxe;
	public static Item BrochantitePickaxe;
	public static Item BrochantiteShard;
	public static Item BrochantiteSpade;
	public static Item CrimsonDye;
	public static Item DoloBlade;
	public static Item DolomiteAxe;
	public static Item DolomitePickaxe;
	public static Item DolomiteShard;
	public static Item DolomiteSpade;
	public static Item FoeBlade;
	public static Item FotiteAxe;
	public static Item FotitePickaxe;
	public static Item FotiteShard;
	public static Item FotiteSpade;
	public static Item GeniteBlade;
	public static Item GrayDye;
	public static Item GreenDye;
	public static Item HeterogeniteAxe;
	public static Item HeterogenitePickaxe;
	public static Item HeterogeniteShard;
	public static Item HeterogeniteSpade;
	public static Item KasoBlade;
	public static Item KasoliteAxe;
	public static Item KasolitePickaxe;
	public static Item KasoliteShard;
	public static Item KasoliteSpade;
	public static Item LazarusBlade;
	public static Item LazuriteAxe;
	public static Item LazuritePickaxe;
	public static Item LazuriteShard;
	public static Item LazuriteSpade;
	public static Item MasterCrystal;
	public static Item PinkDye;
	public static Item RedDye;
	public static Item ScaleBoots;
	public static Item ScaleChestplate;
	public static Item ScaleHelmet;
	public static Item ScaleLeggings;
	public static Item SlimeCannon;
	public static Item SlimeClub;
	public static Item SlimeStabber;
	public static Item SludgeAxe;
	public static Item SludgeHammer;
	public static Item SludgeHoe;
	public static Item SludgePickaxe;
	public static Item SludgeSickle;
	public static Item SludgeSpade;
	public static Item YellowDye;
	
	public static void setupItems() {
		//Item Materials
		EnumToolMaterial InfectedMaterial = EnumHelper.addToolMaterial("Infected Material", 3, 4000, 7.0F, 2, 20);
		EnumToolMaterial SludgeMaterial = EnumHelper.addToolMaterial("Sludge Material", 3, 4500, 7.5F, 3, 20);
		EnumToolMaterial ApophylliteMaterial = EnumHelper.addToolMaterial("Apophyllite Material", 3, 4230, 7.2F, 3, 26);
		EnumToolMaterial AxiniteMaterial = EnumHelper.addToolMaterial("Axinite Material", 3, 4666, 7.3F, 3, 29);
		EnumToolMaterial BetafiteMaterial = EnumHelper.addToolMaterial("Betafite Material", 3, 4950, 7.4F, 4, 30);
		EnumToolMaterial BrochantiteMaterial = EnumHelper.addToolMaterial("Brochantite Material", 4, 5000, 7.9F, 4, 60);
		EnumToolMaterial DolomiteMaterial = EnumHelper.addToolMaterial("Dolomite Material", 3, 4020, 8.0F, 3, 14);
		EnumToolMaterial FotiteMaterial = EnumHelper.addToolMaterial("Fotite Material", 3, 6000, 8.1F, 3, 2);
		EnumToolMaterial GentiteMaterial = EnumHelper.addToolMaterial("Gentite Material", 3, 5750, 7.8F, 3, 9);
		EnumToolMaterial HeterogeniteMaterial = EnumHelper.addToolMaterial("Heterogenite Material", 3, 5100, 7.6F, 3, 8);
		EnumToolMaterial KasoliteMaterial = EnumHelper.addToolMaterial("Kasolite Material", 3, 5678, 7.7F, 3, 20);
		EnumToolMaterial LazuriteMaterial = EnumHelper.addToolMaterial("Lazurite Material", 3, 3500, 6.8F, 3, 20);
		
		//Armor Materials
		EnumArmorMaterial InfectedArmorMaterial = EnumHelper.addArmorMaterial("Infected Armor", 33, new int[] {2, 6, 6, 5}, 16);
		EnumArmorMaterial ScaleArmorMaterial = EnumHelper.addArmorMaterial("Scale Armor", 40, new int[] {3, 7, 7, 6}, 32);
		
		//Item Loading
		ApophylliteCrystal = new ItemCrystal(IDsHelper.ApophylliteCrystalID, "ApophylliteCrystal").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("ApophylliteCrystal");
		AxiniteCrystal = new ItemCrystal(IDsHelper.AxiniteCrystalID, "AxiniteCrystal").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("AxiniteCrystal");
		Banana = new ItemBanana(IDsHelper.BananaID, 2, 2.0F, false).setCreativeTab(ZoneSeek.ZoneSeekFood).setUnlocalizedName("Banana");
		BetafiteCrystal = new ItemCrystal(IDsHelper.BetafiteCrystalID, "BetafiteCrystal").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("BetafiteCrystal");
		BookOfInfection = new ItemBookOfInfecteion(IDsHelper.BookOfInfectionID).setCreativeTab(ZoneSeek.ZoneSeekItems).setUnlocalizedName("BookOfInfectione");
		BrochantiteCrystal = new ItemCrystal(IDsHelper.BrochantiteCrystalID, "BrochantiteCrystal").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("BrochantiteCrystal");
		CoconutChunk = new ItemCoconutChunk(IDsHelper.CoconutChunkID, 2, 2.0F, false).setCreativeTab(ZoneSeek.ZoneSeekFood).setUnlocalizedName("CoconutChunk");
		CompactedScaleFragment = new ItemMisc(IDsHelper.CompactedScaleFragmentID, "CompactedScaleFragment").setCreativeTab(ZoneSeek.ZoneSeekItems).setUnlocalizedName("CompactedScaleFragment");
		CompactedScalePlate = new ItemMisc(IDsHelper.CompactedScalePlateID, "CompactedScalePlate").setCreativeTab(ZoneSeek.ZoneSeekItems).setUnlocalizedName("CompactedScalePlate");
		DolomiteCrystal = new ItemCrystal(IDsHelper.DolomiteCrystalID, "DolomiteCrystal").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("DolomiteCrystal");
		DragonFruit = new ItemDragonFruit(IDsHelper.DragonFruitID, 2, 2.0F, false).setCreativeTab(ZoneSeek.ZoneSeekFood).setUnlocalizedName("DragonFruit");
		FotiteCrystal = new ItemCrystal(IDsHelper.FotiteCrystalID, "FotiteCrystal").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("FotiteCrystal");
		FuzzleChop = new ItemFuzzleChop(IDsHelper.FuzzleChopID, 2, 5.0F, false).setCreativeTab(ZoneSeek.ZoneSeekFood).setUnlocalizedName("FuzzleChop");
		HeterogeniteCrystal = new ItemCrystal(IDsHelper.HeterogeniteCrystalID, "HeterogeniteCrystal").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("HeterogeniteCrystal");
		InfectedArrow = new ItemInfectedArrow(IDsHelper.InfectedArrowID).setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("InfectedArrow");
		InfectedAxe = new ItemInfectedAxe(IDsHelper.InfectedAxeID, InfectedMaterial).setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("InfectedAxe");
		InfectedBattleAxe = new ItemBattleAxe(IDsHelper.InfectedBattleAxeID, InfectedMaterial).setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("InfectedBattleAxe");
		InfectedBoots = new ItemInfectedBoots(IDsHelper.InfectedBootsID, InfectedArmorMaterial, proxy.addArmor("Infected"), 3, "infectedboots").setCreativeTab(ZoneSeek.ZoneSeekArmor).setUnlocalizedName("InfectedBoots");
		InfectedBow = new ItemInfectedBow(IDsHelper.InfectedBowID).setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("InfectedBow");
		InfectedChestplate = new ItemInfectedChestPlate(IDsHelper.InfectedChestplateID, InfectedArmorMaterial, proxy.addArmor("Infected"), 1, "infectedchestplate").setCreativeTab(ZoneSeek.ZoneSeekArmor).setUnlocalizedName("InfectedChestplate");
		InfectedGem = new ItemMisc(IDsHelper.InfectedGemID, "InfectedGem").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("InfectedGem");
		InfectedHelmet = new ItemInfectedHelmet(IDsHelper.InfectedHelmetID, InfectedArmorMaterial, proxy.addArmor("Infected"), 0, "infectedhelmet").setCreativeTab(ZoneSeek.ZoneSeekArmor).setUnlocalizedName("InfectedHelmet");
		InfectedHoe = new ItemInfectedHoe(IDsHelper.InfectedHoeID, InfectedMaterial).setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("InfectedHoe");
		InfectedLeggings = new ItemInfectedLeggings(IDsHelper.InfectedLeggingsID, InfectedArmorMaterial, proxy.addArmor("Infected"), 2, "infectedleggings").setCreativeTab(ZoneSeek.ZoneSeekArmor).setUnlocalizedName("InfectedLeggings");
		InfectedPaxcel = new ItemInfectedPaxcel(IDsHelper.InfectedPaxcelID, InfectedMaterial).setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("InfectedPaxcel");
		InfectedPickaxe = new ItemInfectedPickaxe(IDsHelper.InfectedPickaxeID, InfectedMaterial).setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("InfectedPickaxe");
		InfectedPlate = new ItemMisc(IDsHelper.InfectedPlateID, "InfectedPlate").setCreativeTab(ZoneSeek.ZoneSeekItems).setUnlocalizedName("InfectedPlate");
		InfectedProd = new ItemInfectedProd(IDsHelper.InfectedProdID, InfectedMaterial).setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("InfectedProd");
		InfectedShard = new ItemMisc(IDsHelper.InfectedShardID, "InfectedShard").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("InfectedShard");
		InfectedSpade = new ItemInfectedSpade(IDsHelper.InfectedSpadeID, InfectedMaterial).setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("InfectedSpade");
		InfectedStick = new ItemMisc(IDsHelper.InfectedStickID, "InfectedStick").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("InfectedStick");
		InfectedStone = new ItemMisc(IDsHelper.InfectedStoneID, "InfectedStone").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("InfectedStone");
		InfectedSword = new ItemInfectedSword(IDsHelper.InfectedSwordID, InfectedMaterial).setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("InfectedSword");
		KasoliteCrystal = new ItemCrystal(IDsHelper.KasoliteCrystalID, "KasoliteCrystal").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("KasoliteCrystal");
		LagoonScale = new ItemMisc(IDsHelper.LagoonScaleID, "LagoonScale").setCreativeTab(ZoneSeek.ZoneSeekItems).setUnlocalizedName("LagoonScale");
		LazuriteCrystal = new ItemCrystal(IDsHelper.LazuriteCrystalID, "LazuriteCrystal").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("LazuriteCrystal");
		ObsidianStick = new ItemMisc(IDsHelper.ObsidianStickID, "ObsidianStick").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("ObsidianStick");
		LagoonStick = new ItemMisc(IDsHelper.LagoonStickID, "LagoonStick").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("LagoonStick");
		Pear = new ItemPear(IDsHelper.PearID, 2, 2.0F, false).setCreativeTab(ZoneSeek.ZoneSeekFood).setUnlocalizedName("Pear");
		PincerScale = new ItemMisc(IDsHelper.PincerScaleID, "PincerScale").setCreativeTab(ZoneSeek.ZoneSeekItems).setUnlocalizedName("PincerScale");
		Pineapple = new ItemPineapple(IDsHelper.PineappleID, 2, 3.0F, false).setCreativeTab(ZoneSeek.ZoneSeekFood).setUnlocalizedName("Pineapple");
		Plum = new ItemPlum(IDsHelper.PlumID, 2, 2.0F, false).setCreativeTab(ZoneSeek.ZoneSeekFood).setUnlocalizedName("Plum");
		SludgeGem = new ItemMisc(IDsHelper.SludgeGemID, "SludgeGem").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("SludgeGem");
		SludgeKatana = new ItemSludgeKatana(IDsHelper.SludgeKatanaID, SludgeMaterial).setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("SludgeKatana");
		SludgeShard = new ItemMisc(IDsHelper.SludgeShardID, "SludgeShard").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("SludgeShard");
		SludgeStone = new ItemMisc(IDsHelper.SludgeStoneID, "SludgeStone").setCreativeTab(ZoneSeek.ZoneSeekMaterials).setUnlocalizedName("SludgeStone");
		SlugSlime = new ItemMisc(IDsHelper.SlugSlimeID, "SlugSlime").setCreativeTab(ZoneSeek.ZoneSeekItems).setUnlocalizedName("SlugSlime");
		TaintedInkDrop = new ItemMisc(IDsHelper.TaintedInkDropID, "TaintedInkDrop").setCreativeTab(ZoneSeek.ZoneSeekItems).setUnlocalizedName("TaintedInkDrop");
		TaintedInkSack = new ItemMisc(IDsHelper.TaintedInkSackID, "TaintedInkSack").setCreativeTab(ZoneSeek.ZoneSeekItems).setUnlocalizedName("TaintedInkSack");
		TaintedLeather = new ItemMisc(IDsHelper.TaintedLeatherID, "TaintedLeather").setCreativeTab(ZoneSeek.ZoneSeekItems).setUnlocalizedName("TaintedLeather");
		TaintedPage = new ItemMisc(IDsHelper.TaintedPageID, "TaintedPage").setCreativeTab(ZoneSeek.ZoneSeekItems).setUnlocalizedName("TaintedPage");
		
		//Apophyllite
		ApophylliBlade = new ItemBlade(IDsHelper.ApophylliBladeID, ApophylliteMaterial, "ApophylliBlade").setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("ApophylliBlade");
		ApophylliteAxe = new ItemCustomAxe(IDsHelper.ApophylliteAxeID, ApophylliteMaterial, "ApophylliteAxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("ApophylliteAxe");
		ApophyllitePickaxe = new ItemCustomPickaxe(IDsHelper.ApophyllitePickaxeID, ApophylliteMaterial, "ApophyllitePickaxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("ApophyllitePickaxe");
		ApophylliteSpade = new ItemCustomSpade(IDsHelper.ApophylliteSpadeID, ApophylliteMaterial, "ApophylliteSpade").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("ApophylliteSpade");
		//Axinite
		AxiBlade = new ItemBlade(IDsHelper.AxiBladeID, AxiniteMaterial, "AxiBlade").setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("AxiBlade");
		AxiniteAxe = new ItemCustomAxe(IDsHelper.AxiniteAxeID, AxiniteMaterial, "AxiniteAxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("AxiniteAxe");
		AxinitePickaxe = new ItemCustomPickaxe(IDsHelper.AxinitePickaxeID, AxiniteMaterial, "AxinitePickaxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("AxinitePickaxe");
		AxiniteSpade = new ItemCustomSpade(IDsHelper.AxiniteSpadeID, AxiniteMaterial, "AxiniteSpade").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("AxiniteSpade");
		//Betafite
		BetaBlade = new ItemBlade(IDsHelper.BetaBladeID, BetafiteMaterial, "BetaBlade").setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("BetaBlade");
		BetafiteAxe = new ItemCustomAxe(IDsHelper.BetafiteAxeID, BetafiteMaterial, "BetafiteAxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("BetafiteAxe");
		BetafitePickaxe = new ItemCustomPickaxe(IDsHelper.BetafitePickaxeID, BetafiteMaterial, "BetafitePickaxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("BetafitePickaxe");
		BetafiteSpade = new ItemCustomSpade(IDsHelper.BetafiteSpadeID, BetafiteMaterial, "BetafiteSpade").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("BetafiteSpade");
		//Brochantite
		BroBlade = new ItemBlade(IDsHelper.BroBladeID, BrochantiteMaterial, "BroBlade").setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("BroBlade");
		BrochantiteAxe = new ItemCustomAxe(IDsHelper.BrochantiteAxeID, BrochantiteMaterial, "BrochantiteAxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("BrochantiteAxe");
		BrochantitePickaxe = new ItemCustomPickaxe(IDsHelper.BrochantitePickaxeID, BrochantiteMaterial, "BrochantitePickaxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("BrochantitePickaxe");
		BrochantiteSpade = new ItemCustomSpade(IDsHelper.BrochantiteSpadeID, BrochantiteMaterial, "BrochantiteSpade").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("BrochantiteSpade");
		//Dolomite
		DoloBlade = new ItemBlade(IDsHelper.DoloBladeID, DolomiteMaterial, "DoloBlade").setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("DoloBlade");
		DolomiteAxe = new ItemCustomAxe(IDsHelper.DolomiteAxeID, DolomiteMaterial, "DolomiteAxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("DolomiteAxe");
		DolomitePickaxe = new ItemCustomPickaxe(IDsHelper.DolomitePickaxeID, DolomiteMaterial, "DolomitePickaxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("DolomitePickaxe");
		DolomiteSpade = new ItemCustomSpade(IDsHelper.DolomiteSpadeID, DolomiteMaterial, "DolomiteSpade").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("DolomiteSpade");
		//Fotite
		FoeBlade = new ItemBlade(IDsHelper.FoeBladeID, FotiteMaterial, "FoeBlade").setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("FoeBlade");
		FotiteAxe = new ItemCustomAxe(IDsHelper.FotiteAxeID, FotiteMaterial, "FotiteAxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("FotiteAxe");
		FotitePickaxe = new ItemCustomPickaxe(IDsHelper.FotitePickaxeID, FotiteMaterial, "FotitePickaxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("FotitePickaxe");
		FotiteSpade = new ItemCustomSpade(IDsHelper.FotiteSpadeID, FotiteMaterial, "FotiteSpade").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("FotiteSpade");
		//Heterogenite
		GeniteBlade = new ItemBlade(IDsHelper.GeniteBladeID, HeterogeniteMaterial, "GeniteBlade").setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("GeniteBlade");
		HeterogeniteAxe = new ItemCustomAxe(IDsHelper.HeterogeniteAxeID, HeterogeniteMaterial, "HeterogeniteAxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("HeterogeniteAxe");
		HeterogenitePickaxe = new ItemCustomPickaxe(IDsHelper.HeterogenitePickaxeID, HeterogeniteMaterial, "HeterogenitePickaxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("HeterogenitePickaxe");
		HeterogeniteSpade = new ItemCustomSpade(IDsHelper.HeterogeniteSpadeID, HeterogeniteMaterial, "HeterogeniteSpade").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("HeterogeniteSpade");
		//Kasolite
		KasoBlade = new ItemBlade(IDsHelper.KasoBladeID, KasoliteMaterial, "KasoBlade").setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("KasoBlade");
		KasoliteAxe = new ItemCustomAxe(IDsHelper.KasoliteAxeID, KasoliteMaterial, "KasoliteAxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("KasoliteAxe");
		KasolitePickaxe = new ItemCustomPickaxe(IDsHelper.KasolitePickaxeID, KasoliteMaterial, "KasolitePickaxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("KasolitePickaxe");
		KasoliteSpade = new ItemCustomSpade(IDsHelper.KasoliteSpadeID, KasoliteMaterial, "KasoliteSpade").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("KasoliteSpade");
		//Lazurite
		LazarusBlade = new ItemBlade(IDsHelper.LazarusBladeID, LazuriteMaterial, "LazarusBlade").setCreativeTab(ZoneSeek.ZoneSeekWeapons).setUnlocalizedName("LazarusBlade");
		LazuriteAxe = new ItemCustomAxe(IDsHelper.LazuriteAxeID, LazuriteMaterial, "LazuriteAxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("LazuriteAxe");
		LazuritePickaxe = new ItemCustomPickaxe(IDsHelper.LazuritePickaxeID, LazuriteMaterial, "LazuritePickaxe").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("LazuritePickaxe");
		LazuriteSpade = new ItemCustomSpade(IDsHelper.LazuriteSpadeID, LazuriteMaterial, "LazuriteSpade").setCreativeTab(ZoneSeek.ZoneSeekTools).setUnlocalizedName("LazuriteSpade");
		//Slime
		
		//Scale
		
		//Dye

		gameRegisters();
		languageRegisters();
	}
	
	private static void gameRegisters(){
		//Item Registry
		GameRegistry.registerItem(ApophylliteCrystal, "ApophylliteCrystal");
		GameRegistry.registerItem(AxiniteCrystal, "AxiniteCrystal");
		GameRegistry.registerItem(Banana, "Banana");
		GameRegistry.registerItem(BetafiteCrystal, "BetafiteCrystal");
		GameRegistry.registerItem(BookOfInfection, "BookOfInfectione");
		GameRegistry.registerItem(BrochantiteCrystal, "BrochantiteCrystal");
		GameRegistry.registerItem(CoconutChunk, "CoconutChunk");
		GameRegistry.registerItem(CompactedScaleFragment, "CompactedScaleFragment");
		GameRegistry.registerItem(CompactedScalePlate, "CompactedScalePlate");
		GameRegistry.registerItem(DolomiteCrystal, "DolomiteCrystal");
		GameRegistry.registerItem(DragonFruit, "DragonFruit");
		GameRegistry.registerItem(FotiteCrystal, "FotiteCrystal");
		GameRegistry.registerItem(FuzzleChop, "FuzzleChop");
		GameRegistry.registerItem(HeterogeniteCrystal, "HeterogeniteCrystal");
		GameRegistry.registerItem(InfectedArrow, "InfectedArrow");
		GameRegistry.registerItem(InfectedAxe, "InfectedAxe");
		GameRegistry.registerItem(InfectedBattleAxe, "InfectedBattleAxe");
		GameRegistry.registerItem(InfectedBoots, "InfectedBoots");
		GameRegistry.registerItem(InfectedBow, "InfectedBow");
		GameRegistry.registerItem(InfectedChestplate, "InfectedChestplate");
		GameRegistry.registerItem(InfectedHelmet, "InfectedHelmet");
		GameRegistry.registerItem(InfectedHoe, "InfectedHoe");
		GameRegistry.registerItem(InfectedLeggings, "InfectedLeggings");
		GameRegistry.registerItem(InfectedPaxcel, "InfectedPaxcel");
		GameRegistry.registerItem(InfectedPickaxe, "InfectedPickaxe");
		GameRegistry.registerItem(InfectedPlate, "InfectedPlate");
		GameRegistry.registerItem(InfectedProd, "InfectedProd");
		GameRegistry.registerItem(InfectedShard, "InfectedShard");
		GameRegistry.registerItem(InfectedSpade, "InfectedSpade");
		GameRegistry.registerItem(InfectedStick, "InfectedStick");
		GameRegistry.registerItem(InfectedStone, "InfectedStone");
		GameRegistry.registerItem(InfectedSword, "InfectedSword");
		GameRegistry.registerItem(KasoliteCrystal, "KasoliteCrystal");
		GameRegistry.registerItem(LagoonScale, "LagoonScale");
		GameRegistry.registerItem(LazuriteCrystal, "LazuriteCrystal");
		GameRegistry.registerItem(ObsidianStick, "ObsidianStick");
		GameRegistry.registerItem(Pear, "Pear");
		GameRegistry.registerItem(PincerScale, "PincerScale");
		GameRegistry.registerItem(Pineapple, "Pineapple");
		GameRegistry.registerItem(Plum, "Plum");
		GameRegistry.registerItem(SludgeGem, "SludgeGem");
		GameRegistry.registerItem(SludgeKatana, "SludgeKatana");
		GameRegistry.registerItem(SludgeShard, "SludgeShard");
		GameRegistry.registerItem(SludgeStone, "SludgeStone");
		GameRegistry.registerItem(SlugSlime, "SlugSlime");
		GameRegistry.registerItem(TaintedInkDrop, "TaintedInkDrop");
		GameRegistry.registerItem(TaintedInkSack, "TaintedInkSack");
		GameRegistry.registerItem(TaintedLeather, "TaintedLeather");
		GameRegistry.registerItem(TaintedPage, "TaintedPage");
		GameRegistry.registerItem(InfectedGem, "InfectedGem");
		GameRegistry.registerItem(LagoonStick, "LagoonStick");
		GameRegistry.registerItem(ApophylliBlade, "ApophylliBlade");
		GameRegistry.registerItem(ApophylliteAxe, "ApophylliteAxe");
		GameRegistry.registerItem(ApophyllitePickaxe, "ApophyllitePickaxe");
		GameRegistry.registerItem(ApophylliteSpade, "ApophylliteSpade");
		GameRegistry.registerItem(ApophylliteAxe, "ApophylliteAxe");
		GameRegistry.registerItem(AxiniteAxe, "AxiniteAxe");
		GameRegistry.registerItem(AxinitePickaxe, "AxinitePickaxe");
		GameRegistry.registerItem(AxiniteSpade, "AxiniteSpade");
		GameRegistry.registerItem(BetaBlade, "BetaBlade");
		GameRegistry.registerItem(BetafiteAxe, "BetafiteAxe");
		GameRegistry.registerItem(BetafitePickaxe, "BetafitePickaxe");
		GameRegistry.registerItem(BetafiteSpade, "BetafiteSpade");
		GameRegistry.registerItem(BroBlade, "BroBlade");
		GameRegistry.registerItem(BrochantiteAxe, "BrochantiteAxe");
		GameRegistry.registerItem(BrochantitePickaxe, "BrochantitePickaxe");
		GameRegistry.registerItem(BrochantiteSpade, "BrochantiteSpade");
		GameRegistry.registerItem(DoloBlade, "DoloBlade");
		GameRegistry.registerItem(DolomiteAxe, "DolomiteAxe");
		GameRegistry.registerItem(DolomitePickaxe, "DolomitePickaxe");
		GameRegistry.registerItem(DolomiteSpade, "DolomiteSpade");
		GameRegistry.registerItem(FoeBlade, "FoeBlade");
		GameRegistry.registerItem(FotiteAxe, "FotiteAxe");
		GameRegistry.registerItem(FotitePickaxe, "FotitePickaxe");
		GameRegistry.registerItem(FotiteSpade, "FotiteSpade");
		GameRegistry.registerItem(GeniteBlade, "GeniteBlade");
		GameRegistry.registerItem(HeterogeniteAxe, "HeterogeniteAxe");
		GameRegistry.registerItem(HeterogenitePickaxe, "HeterogenitePickaxe");
		GameRegistry.registerItem(HeterogeniteSpade, "HeterogeniteSpade");
		GameRegistry.registerItem(KasoBlade, "KasoBlade");
		GameRegistry.registerItem(KasoliteAxe, "KasoliteAxe");
		GameRegistry.registerItem(KasolitePickaxe, "KasolitePickaxe");
		GameRegistry.registerItem(KasoliteSpade, "KasoliteSpade");
		GameRegistry.registerItem(LazarusBlade, "LazarusBlade");
		GameRegistry.registerItem(LazuriteAxe, "LazuriteAxe");
		GameRegistry.registerItem(LazuritePickaxe, "LazuritePickaxe");
		GameRegistry.registerItem(LazuriteSpade, "LazuriteSpade");
		
		
	}
	

	private static void languageRegisters(){
		//Item LanguageRegistry
		LanguageRegistry.addName(ApophylliteCrystal, "Apophyllite Crystal");
		LanguageRegistry.addName(AxiniteCrystal, "Axinite Crystal");
		LanguageRegistry.addName(Banana, "Banana");
		LanguageRegistry.addName(BetafiteCrystal, "Betafite Crystal");
		LanguageRegistry.addName(BookOfInfection, "Book Of Infection");
		LanguageRegistry.addName(BrochantiteCrystal, "Brochantite Crystal");
		LanguageRegistry.addName(CoconutChunk, "Coconut Chunk");
		LanguageRegistry.addName(CompactedScaleFragment, "Compacted Scale Fragment");
		LanguageRegistry.addName(CompactedScalePlate, "Compacted Scale Plate");
		LanguageRegistry.addName(DolomiteCrystal, "Dolomite Crystal");
		LanguageRegistry.addName(DragonFruit, "Dragon Fruit");
		LanguageRegistry.addName(FotiteCrystal, "Fotite Crystal");
		LanguageRegistry.addName(FuzzleChop, "Fuzzle Chop");
		LanguageRegistry.addName(HeterogeniteCrystal, "Heterogenite Crystal");
		LanguageRegistry.addName(InfectedArrow, "Infected Arrow");
        LanguageRegistry.addName(InfectedAxe, "Infected Axe");
		LanguageRegistry.addName(InfectedBattleAxe, "Infected Battle Axe");
		LanguageRegistry.addName(InfectedBoots, "Infected Boots");
		LanguageRegistry.addName(InfectedBow, "Infected Bow");
		LanguageRegistry.addName(InfectedChestplate, "Infected Chestplate");
		LanguageRegistry.addName(InfectedGem, "Infected Gem");
		LanguageRegistry.addName(InfectedHelmet, "Infected Helmet");
		LanguageRegistry.addName(InfectedHoe, "Infected Hoe");
		LanguageRegistry.addName(InfectedLeggings, "Infected Leggings");
		LanguageRegistry.addName(InfectedPaxcel, "Infected Paxcel");
		LanguageRegistry.addName(InfectedPickaxe, "Infected Pickaxe");
		LanguageRegistry.addName(InfectedPlate, "Infected Plate");
		LanguageRegistry.addName(InfectedProd, "Infected Prod");
		LanguageRegistry.addName(InfectedShard, "Infected Shard");
		LanguageRegistry.addName(InfectedSpade, "Infected Spade");
		LanguageRegistry.addName(InfectedStick, "Infected Stick");
        LanguageRegistry.addName(InfectedStone, "Infected Stone");
		LanguageRegistry.addName(InfectedSword, "Infected Slasher");
		LanguageRegistry.addName(KasoliteCrystal, "Kasolite Crystal");
		LanguageRegistry.addName(LagoonScale, "Lagoon Scale");
		LanguageRegistry.addName(LazuriteCrystal, "Lazurite Crystal");
		LanguageRegistry.addName(ObsidianStick, "Obsidian Stick");
		LanguageRegistry.addName(Pear, "Pear");
		LanguageRegistry.addName(PincerScale, "Pincer Scale");
		LanguageRegistry.addName(Pineapple, "Pineapple");
		LanguageRegistry.addName(Plum, "Plum");
		LanguageRegistry.addName(SludgeGem, "Sludge Gem");
		LanguageRegistry.addName(SludgeKatana, "Sludge Katana");
		LanguageRegistry.addName(SludgeShard, "Sludge Shard");
		LanguageRegistry.addName(SludgeStone, "Sludge Stone");
		LanguageRegistry.addName(SlugSlime, "Slug Slime");
		LanguageRegistry.addName(TaintedInkDrop, "Tainted Ink Drop");
        LanguageRegistry.addName(TaintedInkSack, "Tainted Ink Sack");
        LanguageRegistry.addName(TaintedLeather, "Tainted Leather");
        LanguageRegistry.addName(TaintedPage, "Tainted Page");
        LanguageRegistry.addName(LagoonStick, "Lagoon Stick");
		LanguageRegistry.addName(ApophylliBlade, "Apophylli Blade");
		LanguageRegistry.addName(ApophylliteAxe, "Apophyllite Axe");
		LanguageRegistry.addName(ApophyllitePickaxe, "Apophyllite Pickaxe");
		LanguageRegistry.addName(ApophylliteSpade, "Apophyllite Spade");
		LanguageRegistry.addName(ApophylliteAxe, "Apophyllite Axe");
		LanguageRegistry.addName(AxiniteAxe, "Axinite Axe");
		LanguageRegistry.addName(AxinitePickaxe, "Axinite Pickaxe");
		LanguageRegistry.addName(AxiniteSpade, "Axinite Spade");
		LanguageRegistry.addName(BetaBlade, "Beta Blade");
		LanguageRegistry.addName(BetafiteAxe, "Betafite Axe");
		LanguageRegistry.addName(BetafitePickaxe, "Betafite Pickaxe");
		LanguageRegistry.addName(BetafiteSpade, "Betafite Spade");
		LanguageRegistry.addName(BroBlade, "Bro Blade");
		LanguageRegistry.addName(BrochantiteAxe, "Brochantite Axe");
		LanguageRegistry.addName(BrochantitePickaxe, "Brochantite Pickaxe");
		LanguageRegistry.addName(BrochantiteSpade, "Brochantite Spade");
		LanguageRegistry.addName(DoloBlade, "Dolo Blade");
		LanguageRegistry.addName(DolomiteAxe, "Dolomite Axe");
		LanguageRegistry.addName(DolomitePickaxe, "Dolomite Pickaxe");
		LanguageRegistry.addName(DolomiteSpade, "Dolomite Spade");
		LanguageRegistry.addName(FoeBlade, "Foe Blade");
		LanguageRegistry.addName(FotiteAxe, "Fotite Axe");
		LanguageRegistry.addName(FotitePickaxe, "Fotite Pickaxe");
		LanguageRegistry.addName(FotiteSpade, "Fotite Spade");
		LanguageRegistry.addName(GeniteBlade, "Genite Blade");
		LanguageRegistry.addName(HeterogeniteAxe, "Heterogenite Axe");
		LanguageRegistry.addName(HeterogenitePickaxe, "Heterogenite Pickaxe");
		LanguageRegistry.addName(HeterogeniteSpade, "Heterogenite Spade");
		LanguageRegistry.addName(KasoBlade, "Kaso Blade");
		LanguageRegistry.addName(KasoliteAxe, "Kasolite Axe");
		LanguageRegistry.addName(KasolitePickaxe, "Kasolite Pickaxe");
		LanguageRegistry.addName(KasoliteSpade, "Kasolite Spade");
		LanguageRegistry.addName(LazarusBlade, "Lazarus Blade");
		LanguageRegistry.addName(LazuriteAxe, "Lazurite Axe");
		LanguageRegistry.addName(LazuritePickaxe, "Lazurite Pickaxe");
		LanguageRegistry.addName(LazuriteSpade, "Lazurite Spade");
	}

}
