package ZoneSeek.common.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelPincer extends ModelBase
{
  //fields
    ModelRenderer Body_L;
    ModelRenderer Body_M;
    ModelRenderer Body_T;
    ModelRenderer Right_Arm_Piece_1;
    ModelRenderer Right_Arm_Piece_2;
    ModelRenderer Right_Foot;
    ModelRenderer Right_Toe;
    ModelRenderer Left_Arm_Piece_1;
    ModelRenderer Left_Arm_Piece_2;
    ModelRenderer Left_Foot;
    ModelRenderer Left_Toe;
    ModelRenderer Back_Right_Arm_Piece_1;
    ModelRenderer Back_Right_Arm_Piece_2;
    ModelRenderer Back_Right_Foot;
    ModelRenderer Back_Right_Toe;
    ModelRenderer Back_Left_Arm_Piece_1;
    ModelRenderer Back_Left_Arm_Piece_2;
    ModelRenderer Back_Left_Foot;
    ModelRenderer Back_Left_Toe;
    ModelRenderer Head;
    ModelRenderer Lower_Pincer_1;
    ModelRenderer Lower_Pincer_2;
    ModelRenderer Upper_Right_Pincer_1;
    ModelRenderer Upper_Left_PIncer_1;
    ModelRenderer Upper_Right_Pincer_2;
    ModelRenderer Upper_Left_Pincer_2;
    ModelRenderer Rigth_Eye;
    ModelRenderer Left_Eye;
    ModelRenderer Top_Head_Piece;
    ModelRenderer Bottom_Chest;
  
  public ModelPincer()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Body_L = new ModelRenderer(this, 0, 0);
      Body_L.addBox(-3F, 0F, -7F, 6, 3, 15);
      Body_L.setRotationPoint(0F, 17F, 0F);
      Body_L.setTextureSize(128, 128);
      Body_L.mirror = true;
      setRotation(Body_L, 0F, 0F, 0F);
      Body_M = new ModelRenderer(this, 42, 0);
      Body_M.addBox(-2F, -1F, -6F, 4, 1, 13);
      Body_M.setRotationPoint(0F, 17F, 0F);
      Body_M.setTextureSize(128, 128);
      Body_M.mirror = true;
      setRotation(Body_M, 0F, 0F, 0F);
      Body_T = new ModelRenderer(this, 32, 0);
      Body_T.addBox(-1F, -2F, -3F, 2, 1, 7);
      Body_T.setRotationPoint(0F, 17F, 0F);
      Body_T.setTextureSize(128, 128);
      Body_T.mirror = true;
      setRotation(Body_T, 0F, 0F, 0F);
      Right_Arm_Piece_1 = new ModelRenderer(this, 0, 19);
      Right_Arm_Piece_1.addBox(0F, 0F, 0F, 5, 1, 2);
      Right_Arm_Piece_1.setRotationPoint(3F, 19F, -4F);
      Right_Arm_Piece_1.setTextureSize(128, 128);
      Right_Arm_Piece_1.mirror = true;
      setRotation(Right_Arm_Piece_1, 0F, -0.6283185F, 0F);
      Right_Arm_Piece_2 = new ModelRenderer(this, 17, 26);
      Right_Arm_Piece_2.addBox(2F, 2.5F, -3F, 2, 1, 5);
      Right_Arm_Piece_2.setRotationPoint(3F, 19F, -4F);
      Right_Arm_Piece_2.setTextureSize(128, 128);
      Right_Arm_Piece_2.mirror = true;
      setRotation(Right_Arm_Piece_2, 0.7063936F, 0F, 0F);
      Right_Foot = new ModelRenderer(this, 0, 0);
      Right_Foot.addBox(2F, 4F, -2F, 2, 1, 2);
      Right_Foot.setRotationPoint(3F, 19F, -4F);
      Right_Foot.setTextureSize(128, 128);
      Right_Foot.mirror = true;
      setRotation(Right_Foot, 0F, 0F, 0F);
      Right_Toe = new ModelRenderer(this, 0, 5);
      Right_Toe.addBox(2F, 4F, -3F, 1, 1, 1);
      Right_Toe.setRotationPoint(3F, 19F, -4F);
      Right_Toe.setTextureSize(128, 128);
      Right_Toe.mirror = true;
      setRotation(Right_Toe, 0F, 0F, 0F);
      Left_Arm_Piece_1 = new ModelRenderer(this, 15, 19);
      Left_Arm_Piece_1.addBox(0F, 0F, 0F, 2, 1, 5);
      Left_Arm_Piece_1.setRotationPoint(-3F, 19F, -4F);
      Left_Arm_Piece_1.setTextureSize(128, 128);
      Left_Arm_Piece_1.mirror = true;
      setRotation(Left_Arm_Piece_1, 0F, -0.93666F, 0F);
      Left_Arm_Piece_2 = new ModelRenderer(this, 0, 23);
      Left_Arm_Piece_2.addBox(-4F, 2.5F, -3F, 2, 1, 5);
      Left_Arm_Piece_2.setRotationPoint(-3F, 19F, -4F);
      Left_Arm_Piece_2.setTextureSize(128, 128);
      Left_Arm_Piece_2.mirror = true;
      setRotation(Left_Arm_Piece_2, 0.7063936F, 0F, 0F);
      Left_Foot = new ModelRenderer(this, 0, 0);
      Left_Foot.addBox(-4F, 4F, -2F, 2, 1, 2);
      Left_Foot.setRotationPoint(-3F, 19F, -4F);
      Left_Foot.setTextureSize(128, 128);
      Left_Foot.mirror = true;
      setRotation(Left_Foot, 0F, 0F, 0F);
      Left_Toe = new ModelRenderer(this, 0, 5);
      Left_Toe.addBox(-3F, 4F, -3F, 1, 1, 1);
      Left_Toe.setRotationPoint(-3F, 19F, -4F);
      Left_Toe.setTextureSize(128, 128);
      Left_Toe.mirror = true;
      setRotation(Left_Toe, 0F, 0F, 0F);
      Back_Right_Arm_Piece_1 = new ModelRenderer(this, 0, 19);
      Back_Right_Arm_Piece_1.addBox(0F, 0F, 0F, 5, 1, 2);
      Back_Right_Arm_Piece_1.setRotationPoint(3F, 19F, 5F);
      Back_Right_Arm_Piece_1.setTextureSize(128, 128);
      Back_Right_Arm_Piece_1.mirror = true;
      setRotation(Back_Right_Arm_Piece_1, 0F, -0.6283185F, 0F);
      Back_Right_Arm_Piece_2 = new ModelRenderer(this, 17, 26);
      Back_Right_Arm_Piece_2.addBox(2F, 2.5F, -3F, 2, 1, 5);
      Back_Right_Arm_Piece_2.setRotationPoint(3F, 19F, 5F);
      Back_Right_Arm_Piece_2.setTextureSize(128, 128);
      Back_Right_Arm_Piece_2.mirror = true;
      setRotation(Back_Right_Arm_Piece_2, 0.7063936F, 0F, 0F);
      Back_Right_Foot = new ModelRenderer(this, 0, 0);
      Back_Right_Foot.addBox(2F, 4F, -2F, 2, 1, 2);
      Back_Right_Foot.setRotationPoint(3F, 19F, 5F);
      Back_Right_Foot.setTextureSize(128, 128);
      Back_Right_Foot.mirror = true;
      setRotation(Back_Right_Foot, 0F, 0F, 0F);
      Back_Right_Toe = new ModelRenderer(this, 0, 5);
      Back_Right_Toe.addBox(2F, 4F, -3F, 1, 1, 1);
      Back_Right_Toe.setRotationPoint(3F, 19F, 5F);
      Back_Right_Toe.setTextureSize(128, 128);
      Back_Right_Toe.mirror = true;
      setRotation(Back_Right_Toe, 0F, 0F, 0F);
      Back_Left_Arm_Piece_1 = new ModelRenderer(this, 15, 19);
      Back_Left_Arm_Piece_1.addBox(0F, 0F, 0F, 2, 1, 5);
      Back_Left_Arm_Piece_1.setRotationPoint(-3F, 19F, 5F);
      Back_Left_Arm_Piece_1.setTextureSize(128, 128);
      Back_Left_Arm_Piece_1.mirror = true;
      setRotation(Back_Left_Arm_Piece_1, 0F, -0.93666F, 0F);
      Back_Left_Arm_Piece_2 = new ModelRenderer(this, 0, 23);
      Back_Left_Arm_Piece_2.addBox(-4F, 2.5F, -3F, 2, 1, 5);
      Back_Left_Arm_Piece_2.setRotationPoint(-3F, 19F, 5F);
      Back_Left_Arm_Piece_2.setTextureSize(128, 128);
      Back_Left_Arm_Piece_2.mirror = true;
      setRotation(Back_Left_Arm_Piece_2, 0.7063936F, 0F, 0F);
      Back_Left_Foot = new ModelRenderer(this, 0, 0);
      Back_Left_Foot.addBox(-4F, 4F, -2F, 2, 1, 2);
      Back_Left_Foot.setRotationPoint(-3F, 19F, 5F);
      Back_Left_Foot.setTextureSize(128, 128);
      Back_Left_Foot.mirror = true;
      setRotation(Back_Left_Foot, 0F, 0F, 0F);
      Back_Left_Toe = new ModelRenderer(this, 0, 5);
      Back_Left_Toe.addBox(-3F, 4F, -3F, 1, 1, 1);
      Back_Left_Toe.setRotationPoint(-3F, 19F, 5F);
      Back_Left_Toe.setTextureSize(128, 128);
      Back_Left_Toe.mirror = true;
      setRotation(Back_Left_Toe, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 31);
      Head.addBox(-2F, -3F, -5F, 4, 4, 5);
      Head.setRotationPoint(0F, 19F, -7F);
      Head.setTextureSize(128, 128);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Lower_Pincer_1 = new ModelRenderer(this, 0, 41);
      Lower_Pincer_1.addBox(-0.5F, 0F, -8F, 1, 1, 3);
      Lower_Pincer_1.setRotationPoint(0F, 19F, -7F);
      Lower_Pincer_1.setTextureSize(128, 128);
      Lower_Pincer_1.mirror = true;
      setRotation(Lower_Pincer_1, 0F, 0F, 0F);
      Lower_Pincer_2 = new ModelRenderer(this, 0, 47);
      Lower_Pincer_2.addBox(-0.5F, -0.5F, -10F, 1, 1, 2);
      Lower_Pincer_2.setRotationPoint(0F, 19F, -7F);
      Lower_Pincer_2.setTextureSize(128, 128);
      Lower_Pincer_2.mirror = true;
      setRotation(Lower_Pincer_2, 0F, 0F, 0F);
      Upper_Right_Pincer_1 = new ModelRenderer(this, 0, 41);
      Upper_Right_Pincer_1.addBox(0.5F, -3F, -8F, 1, 1, 3);
      Upper_Right_Pincer_1.setRotationPoint(0F, 19F, -7F);
      Upper_Right_Pincer_1.setTextureSize(128, 128);
      Upper_Right_Pincer_1.mirror = true;
      setRotation(Upper_Right_Pincer_1, 0F, 0F, 0F);
      Upper_Left_PIncer_1 = new ModelRenderer(this, 0, 41);
      Upper_Left_PIncer_1.addBox(-1.5F, -3F, -8F, 1, 1, 3);
      Upper_Left_PIncer_1.setRotationPoint(0F, 19F, -7F);
      Upper_Left_PIncer_1.setTextureSize(128, 128);
      Upper_Left_PIncer_1.mirror = true;
      setRotation(Upper_Left_PIncer_1, 0F, 0F, 0F);
      Upper_Right_Pincer_2 = new ModelRenderer(this, 8, 47);
      Upper_Right_Pincer_2.addBox(0.5F, -2.5F, -10F, 1, 1, 2);
      Upper_Right_Pincer_2.setRotationPoint(0F, 19F, -7F);
      Upper_Right_Pincer_2.setTextureSize(128, 128);
      Upper_Right_Pincer_2.mirror = true;
      setRotation(Upper_Right_Pincer_2, 0F, 0F, 0F);
      Upper_Left_Pincer_2 = new ModelRenderer(this, 8, 47);
      Upper_Left_Pincer_2.addBox(-1.5F, -2.5F, -10F, 1, 1, 2);
      Upper_Left_Pincer_2.setRotationPoint(0F, 19F, -7F);
      Upper_Left_Pincer_2.setTextureSize(128, 128);
      Upper_Left_Pincer_2.mirror = true;
      setRotation(Upper_Left_Pincer_2, 0F, 0F, 0F);
      Rigth_Eye = new ModelRenderer(this, 0, 55);
      Rigth_Eye.addBox(2F, -2F, -3F, 2, 2, 1);
      Rigth_Eye.setRotationPoint(0F, 19F, -7F);
      Rigth_Eye.setTextureSize(128, 128);
      Rigth_Eye.mirror = true;
      setRotation(Rigth_Eye, 0F, 0F, 0F);
      Left_Eye = new ModelRenderer(this, 0, 55);
      Left_Eye.addBox(-4F, -2F, -3F, 2, 2, 1);
      Left_Eye.setRotationPoint(0F, 19F, -7F);
      Left_Eye.setTextureSize(128, 128);
      Left_Eye.mirror = true;
      setRotation(Left_Eye, 0F, 0F, 0F);
      Top_Head_Piece = new ModelRenderer(this, 0, 61);
      Top_Head_Piece.addBox(-0.5F, -3.5F, -5F, 1, 1, 5);
      Top_Head_Piece.setRotationPoint(0F, 19F, -7F);
      Top_Head_Piece.setTextureSize(128, 128);
      Top_Head_Piece.mirror = true;
      setRotation(Top_Head_Piece, 0F, 0F, 0F);
      Bottom_Chest = new ModelRenderer(this, 45, 16);
      Bottom_Chest.addBox(-2F, 3F, -6F, 4, 1, 13);
      Bottom_Chest.setRotationPoint(0F, 17F, 0F);
      Bottom_Chest.setTextureSize(128, 128);
      Bottom_Chest.mirror = true;
      setRotation(Bottom_Chest, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
    super.render(par1Entity, par2, par3, par4, par5, par6, par7);
    setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    Body_L.render(par7);
    Body_M.render(par7);
    Body_T.render(par7);
    Right_Arm_Piece_1.render(par7);
    Right_Arm_Piece_2.render(par7);
    Right_Foot.render(par7);
    Right_Toe.render(par7);
    Left_Arm_Piece_1.render(par7);
    Left_Arm_Piece_2.render(par7);
    Left_Foot.render(par7);
    Left_Toe.render(par7);
    Back_Right_Arm_Piece_1.render(par7);
    Back_Right_Arm_Piece_2.render(par7);
    Back_Right_Foot.render(par7);
    Back_Right_Toe.render(par7);
    Back_Left_Arm_Piece_1.render(par7);
    Back_Left_Arm_Piece_2.render(par7);
    Back_Left_Foot.render(par7);
    Back_Left_Toe.render(par7);
    Head.render(par7);
    Lower_Pincer_1.render(par7);
    Lower_Pincer_2.render(par7);
    Upper_Right_Pincer_1.render(par7);
    Upper_Left_PIncer_1.render(par7);
    Upper_Right_Pincer_2.render(par7);
    Upper_Left_Pincer_2.render(par7);
    Rigth_Eye.render(par7);
    Left_Eye.render(par7);
    Top_Head_Piece.render(par7);
    Bottom_Chest.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
      this.Head.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Head.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Top_Head_Piece.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Top_Head_Piece.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Left_Eye.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Left_Eye.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Rigth_Eye.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Rigth_Eye.rotateAngleX = par5 / (180F / (float)Math.PI);
      /**float f6 = ((float)Math.PI / 4F);
      this.Right_Arm_Piece_1.rotateAngleZ = -f6;
      this.Right_Arm_Piece_2.rotateAngleZ = -f6;
      this.Right_Foot.rotateAngleZ = -f6;
      this.Right_Toe.rotateAngleZ = -f6;
      this.Left_Arm_Piece_1.rotateAngleZ = f6;
      this.Left_Arm_Piece_2.rotateAngleZ = f6;
      this.Left_Foot.rotateAngleZ = f6;
      this.Left_Toe.rotateAngleZ = f6;
      this.Back_Right_Arm_Piece_1.rotateAngleZ = -f6 * 0.74F;
      this.Back_Right_Arm_Piece_2.rotateAngleZ = -f6 * 0.74F;
      this.Back_Right_Foot.rotateAngleZ = -f6 * 0.74F;
      this.Back_Right_Toe.rotateAngleZ = -f6 * 0.74F;
      this.Back_Left_Arm_Piece_1.rotateAngleZ = f6 * 0.74F;
      this.Back_Left_Arm_Piece_2.rotateAngleZ = f6 * 0.74F;
      this.Back_Left_Foot.rotateAngleZ = f6 * 0.74F;
      this.Back_Left_Toe.rotateAngleZ = f6 * 0.74F;
      float f7 = -0.0F;
      float f8 = 0.3926991F;
      this.Right_Arm_Piece_1.rotateAngleY = f8 * 2.0F + f7;
      this.Right_Arm_Piece_2.rotateAngleY = f8 * 2.0F + f7;
      this.Right_Foot.rotateAngleY = f8 * 2.0F + f7;
      this.Right_Toe.rotateAngleY = f8 * 2.0F + f7;
      this.Left_Arm_Piece_1.rotateAngleY = -f8 * 2.0F - f7;
      this.Left_Arm_Piece_2.rotateAngleY = -f8 * 2.0F - f7;
      this.Left_Foot.rotateAngleY = -f8 * 2.0F - f7;
      this.Left_Toe.rotateAngleY = -f8 * 2.0F - f7;
      this.Back_Right_Arm_Piece_1.rotateAngleY = f8 * 1.0F + f7;
      this.Back_Right_Arm_Piece_2.rotateAngleY = f8 * 1.0F + f7;
      this.Back_Right_Foot.rotateAngleY = f8 * 1.0F + f7;
      this.Back_Right_Toe.rotateAngleY = f8 * 1.0F + f7;
      this.Back_Left_Arm_Piece_1.rotateAngleY = -f8 * 1.0F - f7;
      this.Back_Left_Arm_Piece_2.rotateAngleY = -f8 * 1.0F - f7;
      this.Back_Left_Foot.rotateAngleY = -f8 * 1.0F - f7;
      this.Back_Left_Toe.rotateAngleY = -f8 * 1.0F - f7;**/
      float f9 = -(MathHelper.cos(par1 * 0.6662F * 2.0F + 0.0F) * 0.4F) * par2;
      float f10 = -(MathHelper.cos(par1 * 0.6662F * 2.0F + (float)Math.PI) * 0.4F) * par2;
      float f11 = -(MathHelper.cos(par1 * 0.6662F * 2.0F + ((float)Math.PI / 2F)) * 0.4F) * par2;
      float f12 = -(MathHelper.cos(par1 * 0.6662F * 2.0F + ((float)Math.PI * 3F / 2F)) * 0.4F) * par2;
      float f13 = Math.abs(MathHelper.sin(par1 * 0.6662F + 0.0F) * 0.4F) * par2;
      float f14 = Math.abs(MathHelper.sin(par1 * 0.6662F + (float)Math.PI) * 0.4F) * par2;
      float f15 = Math.abs(MathHelper.sin(par1 * 0.6662F + ((float)Math.PI / 2F)) * 0.4F) * par2;
      float f16 = Math.abs(MathHelper.sin(par1 * 0.6662F + ((float)Math.PI * 3F / 2F)) * 0.4F) * par2;
      this.Right_Arm_Piece_1.rotateAngleY += f9;
      this.Right_Arm_Piece_2.rotateAngleY += f9;
      this.Right_Foot.rotateAngleY += f9;
      this.Right_Toe.rotateAngleY += f9;
      
      this.Left_Arm_Piece_1.rotateAngleY += -f9;
      this.Left_Arm_Piece_2.rotateAngleY += -f9;
      this.Left_Foot.rotateAngleY += -f9;
      this.Left_Toe.rotateAngleY += -f9;
      
      this.Back_Right_Arm_Piece_1.rotateAngleY += f10;
      this.Back_Right_Arm_Piece_2.rotateAngleY += f10;
      this.Back_Right_Foot.rotateAngleY += f10;
      this.Back_Right_Toe.rotateAngleY += f10;
      
      this.Back_Left_Arm_Piece_1.rotateAngleY += -f10;
      this.Back_Left_Arm_Piece_2.rotateAngleY += -f10;
      this.Back_Left_Foot.rotateAngleY += -f10;
      this.Back_Left_Toe.rotateAngleY += -f10;
      

      this.Right_Arm_Piece_1.rotateAngleZ += f13;
      this.Right_Arm_Piece_2.rotateAngleZ += f13;
      this.Right_Foot.rotateAngleZ += f13;
      this.Right_Toe.rotateAngleZ += f13;
      
      this.Left_Arm_Piece_1.rotateAngleZ += -f13;
      this.Left_Arm_Piece_2.rotateAngleZ += -f13;
      this.Left_Foot.rotateAngleZ += -f13;
      this.Left_Toe.rotateAngleZ += -f13;
      
      this.Back_Right_Arm_Piece_1.rotateAngleZ += f14;
      this.Back_Right_Arm_Piece_2.rotateAngleZ += f14;
      this.Back_Right_Foot.rotateAngleZ += f14;
      this.Back_Right_Toe.rotateAngleZ += f14;
      
      this.Back_Left_Arm_Piece_1.rotateAngleZ += -f14;
      this.Back_Left_Arm_Piece_2.rotateAngleZ += -f14;
      this.Back_Left_Foot.rotateAngleZ += -f14;
      this.Back_Left_Toe.rotateAngleZ += -f14;

  }

}
