package ZoneSeek.common.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOrthrus extends ModelBase
{
  //fields
    ModelRenderer WolfHead;
    ModelRenderer Body;
    ModelRenderer Mane;
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Tail;
    ModelRenderer Ear1;
    ModelRenderer Ear2;
    ModelRenderer Nose;
    ModelRenderer WolfHead2;
    ModelRenderer Nose2;
    ModelRenderer Ear3;
    ModelRenderer Ear4;
    ModelRenderer Right_Wing_1;
    ModelRenderer Right_Wing_2;
    ModelRenderer Left_Wing_1;
    ModelRenderer Left_Wing_2;
    ModelRenderer R_Wing_1;
    ModelRenderer R_Wing_2;
    ModelRenderer L_Wing_1;
    ModelRenderer Spike_1;
    ModelRenderer Spike_2;
    ModelRenderer Spike_3;
    ModelRenderer R_Wing_3;
  
  public ModelOrthrus()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      WolfHead = new ModelRenderer(this, 0, 0);
      WolfHead.addBox(-7F, -3F, -2F, 6, 6, 4);
      WolfHead.setRotationPoint(-1F, 13.5F, -7F);
      WolfHead.setTextureSize(64, 64);
      WolfHead.mirror = true;
      setRotation(WolfHead, 0F, 0F, 0F);
      Body = new ModelRenderer(this, 18, 14);
      Body.addBox(-3F, -2F, -3F, 6, 9, 6);
      Body.setRotationPoint(-1F, 14F, 2F);
      Body.setTextureSize(64, 64);
      Body.mirror = true;
      setRotation(Body, 1.570796F, 0F, 0F);
      Mane = new ModelRenderer(this, 21, 0);
      Mane.addBox(-4F, -3F, -3F, 8, 6, 7);
      Mane.setRotationPoint(-1F, 14F, -3F);
      Mane.setTextureSize(64, 64);
      Mane.mirror = true;
      setRotation(Mane, 1.570796F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 0, 18);
      Leg1.addBox(-1F, 0F, -1F, 2, 8, 2);
      Leg1.setRotationPoint(-2.5F, 16F, 7F);
      Leg1.setTextureSize(64, 64);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 42, 18);
      Leg2.addBox(-1F, 0F, -1F, 2, 8, 2);
      Leg2.setRotationPoint(0.5F, 16F, 7F);
      Leg2.setTextureSize(64, 64);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 18);
      Leg3.addBox(-1F, 0F, -1F, 2, 8, 2);
      Leg3.setRotationPoint(-2.5F, 16F, -4F);
      Leg3.setTextureSize(64, 64);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 42, 18);
      Leg4.addBox(-1F, 0F, -1F, 2, 8, 2);
      Leg4.setRotationPoint(0.5F, 16F, -4F);
      Leg4.setTextureSize(64, 64);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 9, 18);
      Tail.addBox(-1F, 0F, -1F, 2, 8, 2);
      Tail.setRotationPoint(-1F, 12F, 8F);
      Tail.setTextureSize(64, 64);
      Tail.mirror = true;
      setRotation(Tail, 1.130069F, 0F, 0F);
      Ear1 = new ModelRenderer(this, 16, 14);
      Ear1.addBox(-7F, -5F, 0F, 2, 2, 1);
      Ear1.setRotationPoint(-1F, 13.5F, -7F);
      Ear1.setTextureSize(64, 64);
      Ear1.mirror = true;
      setRotation(Ear1, 0F, 0F, 0F);
      Ear2 = new ModelRenderer(this, 16, 14);
      Ear2.addBox(-3F, -5F, 0F, 2, 2, 1);
      Ear2.setRotationPoint(-1F, 13.5F, -7F);
      Ear2.setTextureSize(64, 64);
      Ear2.mirror = true;
      setRotation(Ear2, 0F, 0F, 0F);
      Nose = new ModelRenderer(this, 0, 10);
      Nose.addBox(-5.5F, 0F, -5F, 3, 3, 4);
      Nose.setRotationPoint(-1F, 13.5F, -7F);
      Nose.setTextureSize(64, 64);
      Nose.mirror = true;
      setRotation(Nose, 0F, 0F, 0F);
      WolfHead2 = new ModelRenderer(this, 0, 31);
      WolfHead2.addBox(1F, -3F, -2F, 6, 6, 4);
      WolfHead2.setRotationPoint(-1F, 13.5F, -7F);
      WolfHead2.setTextureSize(64, 64);
      WolfHead2.mirror = true;
      setRotation(WolfHead2, 0F, 0F, 0F);
      Nose2 = new ModelRenderer(this, 0, 41);
      Nose2.addBox(2.5F, 0F, -5F, 3, 3, 4);
      Nose2.setRotationPoint(-1F, 13.5F, -7F);
      Nose2.setTextureSize(64, 64);
      Nose2.mirror = true;
      setRotation(Nose2, 0F, 0F, 0F);
      Ear3 = new ModelRenderer(this, 16, 42);
      Ear3.addBox(1F, -5F, 0F, 2, 2, 1);
      Ear3.setRotationPoint(-1F, 13.5F, -7F);
      Ear3.setTextureSize(64, 64);
      Ear3.mirror = true;
      setRotation(Ear3, 0F, 0F, 0F);
      Ear4 = new ModelRenderer(this, 16, 42);
      Ear4.addBox(5F, -5F, 0F, 2, 2, 1);
      Ear4.setRotationPoint(-1F, 13.5F, -7F);
      Ear4.setTextureSize(64, 64);
      Ear4.mirror = true;
      setRotation(Ear4, 0F, 0F, 0F);
      Right_Wing_1 = new ModelRenderer(this, 0, 51);
      Right_Wing_1.addBox(2F, 0F, -5F, 7, 1, 1);
      Right_Wing_1.setRotationPoint(-1F, 14F, 2F);
      Right_Wing_1.setTextureSize(64, 64);
      Right_Wing_1.mirror = true;
      setRotation(Right_Wing_1, 0F, 0F, -0.7330383F);
      Right_Wing_2 = new ModelRenderer(this, 0, 54);
      Right_Wing_2.addBox(1F, -9F, -5F, 5, 1, 1);
      Right_Wing_2.setRotationPoint(-1F, 14F, 2F);
      Right_Wing_2.setTextureSize(64, 64);
      Right_Wing_2.mirror = true;
      setRotation(Right_Wing_2, 0F, 0F, 0.7330383F);
      Left_Wing_1 = new ModelRenderer(this, 0, 51);
      Left_Wing_1.addBox(2F, -2F, -5F, 7, 1, 1);
      Left_Wing_1.setRotationPoint(-1F, 14F, 2F);
      Left_Wing_1.setTextureSize(64, 64);
      Left_Wing_1.mirror = true;
      setRotation(Left_Wing_1, 0F, 0F, -2.303835F);
      Left_Wing_2 = new ModelRenderer(this, 0, 54);
      Left_Wing_2.addBox(1.2F, 8F, -5F, 5, 1, 1);
      Left_Wing_2.setRotationPoint(-1F, 14F, 2F);
      Left_Wing_2.setTextureSize(64, 64);
      Left_Wing_2.mirror = true;
      setRotation(Left_Wing_2, 0F, 0F, 2.452549F);
      R_Wing_1 = new ModelRenderer(this, 21, 30);
      R_Wing_1.addBox(1.6F, 0.5F, -5F, 7, 0, 8);
      R_Wing_1.setRotationPoint(-1F, 14F, 2F);
      R_Wing_1.setTextureSize(64, 64);
      R_Wing_1.mirror = true;
      setRotation(R_Wing_1, 0F, 0F, -0.7330383F);
      R_Wing_2 = new ModelRenderer(this, 24, 39);
      R_Wing_2.addBox(1.5F, -8.5F, -5F, 4, 0, 7);
      R_Wing_2.setRotationPoint(-1F, 14F, 2F);
      R_Wing_2.setTextureSize(64, 64);
      R_Wing_2.mirror = true;
      setRotation(R_Wing_2, 0F, 0F, 0.7330383F);
      L_Wing_1 = new ModelRenderer(this, 21, 30);
      L_Wing_1.addBox(1.6F, -1.5F, -5F, 7, 0, 8);
      L_Wing_1.setRotationPoint(-1F, 14F, 2F);
      L_Wing_1.setTextureSize(64, 64);
      L_Wing_1.mirror = true;
      setRotation(L_Wing_1, 0F, 0F, -2.303835F);
      Spike_1 = new ModelRenderer(this, 18, 48);
      Spike_1.addBox(-0.5F, -8F, -6F, 1, 5, 1);
      Spike_1.setRotationPoint(-1F, 14F, 2F);
      Spike_1.setTextureSize(64, 64);
      Spike_1.mirror = true;
      setRotation(Spike_1, 0F, 0F, 0F);
      Spike_2 = new ModelRenderer(this, 18, 48);
      Spike_2.addBox(-0.5F, -7F, -3F, 1, 5, 1);
      Spike_2.setRotationPoint(-1F, 14F, 2F);
      Spike_2.setTextureSize(64, 64);
      Spike_2.mirror = true;
      setRotation(Spike_2, 0F, 0F, 0F);
      Spike_3 = new ModelRenderer(this, 18, 48);
      Spike_3.addBox(-0.5F, -6F, 0F, 1, 5, 1);
      Spike_3.setRotationPoint(-1F, 14F, 2F);
      Spike_3.setTextureSize(64, 64);
      Spike_3.mirror = true;
      setRotation(Spike_3, 0F, 0F, 0F);
      R_Wing_3 = new ModelRenderer(this, 24, 39);
      R_Wing_3.addBox(1.6F, 8.5F, -5F, 4, 0, 7);
      R_Wing_3.setRotationPoint(-1F, 14F, 2F);
      R_Wing_3.setTextureSize(64, 64);
      R_Wing_3.mirror = true;
      setRotation(R_Wing_3, 0F, 0F, 2.452554F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
    super.render(par1Entity, par2, par3, par4, par5, par6, par7);
    setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    WolfHead.render(par7);
    Body.render(par7);
    Mane.render(par7);
    Leg1.render(par7);
    Leg2.render(par7);
    Leg3.render(par7);
    Leg4.render(par7);
    Tail.render(par7);
    Ear1.render(par7);
    Ear2.render(par7);
    Nose.render(par7);
    WolfHead2.render(par7);
    Nose2.render(par7);
    Ear3.render(par7);
    Ear4.render(par7);
    Right_Wing_1.render(par7);
    Right_Wing_2.render(par7);
    Left_Wing_1.render(par7);
    Left_Wing_2.render(par7);
    R_Wing_1.render(par7);
    R_Wing_2.render(par7);
    L_Wing_1.render(par7);
    Spike_1.render(par7);
    Spike_2.render(par7);
    Spike_3.render(par7);
    R_Wing_3.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
      super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
      this.WolfHead.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.WolfHead.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Ear1.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Ear1.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Ear2.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Ear2.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Ear3.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Ear3.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Ear4.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Ear4.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Nose.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Nose.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Nose2.rotateAngleX = par5 / (180F / (float)Math.PI);
      this.Nose2.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Tail.rotateAngleX = par3;
  }

}
